language: python
python:
  - "2.7"
  - "3.4"


install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install nose
  - pip install coveralls
  - pip install Flask-Testing

script:
  - nosetests --nocapture --with-coverage --cover-package=plate
before_script:
  - flake8 --count --exclude ./tests,./doc --ignore E402,F401,E501

after_success:
  - coveralls
